// Comprehensive list of well-known ETF names
// This is used as a fallback when API is not available or for quick lookups

export const KNOWN_ETF_NAMES: Record<string, string> = {
  // Vanguard ETFs
  VOO: "Vanguard S&P 500 ETF",
  VTI: "Vanguard Total Stock Market ETF",
  VTV: "Vanguard Value ETF",
  VUG: "Vanguard Growth ETF",
  VIG: "Vanguard Dividend Appreciation ETF",
  VYM: "Vanguard High Dividend Yield ETF",
  BND: "Vanguard Total Bond Market ETF",
  VXUS: "Vanguard Total International Stock ETF",
  VNQ: "Vanguard Real Estate ETF",
  VO: "Vanguard Mid-Cap ETF",
  VB: "Vanguard Small-Cap ETF",
  VEA: "Vanguard FTSE Developed Markets ETF",
  VWO: "Vanguard FTSE Emerging Markets ETF",
  VTEB: "Vanguard Tax-Exempt Bond ETF",
  VGT: "Vanguard Information Technology ETF",
  VCSH: "Vanguard Short-Term Corporate Bond ETF",
  VCIT: "Vanguard Intermediate-Term Corporate Bond ETF",
  VCLT: "Vanguard Long-Term Corporate Bond ETF",
  VGSH: "Vanguard Short-Term Treasury ETF",
  VGIT: "Vanguard Intermediate-Term Treasury ETF",
  VGLT: "Vanguard Long-Term Treasury ETF",
  VMBS: "Vanguard Mortgage-Backed Securities ETF",
  VDC: "Vanguard Consumer Staples ETF",
  VCR: "Vanguard Consumer Discretionary ETF",
  VDE: "Vanguard Energy ETF",
  VFH: "Vanguard Financials ETF",
  VHT: "Vanguard Health Care ETF",
  VIS: "Vanguard Industrials ETF",
  VPU: "Vanguard Utilities ETF",
  VAW: "Vanguard Materials ETF",
  VGK: "Vanguard FTSE Europe ETF",
  VPL: "Vanguard FTSE Pacific ETF",
  VNQI: "Vanguard Global ex-U.S. Real Estate ETF",
  VSS: "Vanguard FTSE All-World ex-US Small-Cap ETF",
  VT: "Vanguard Total World Stock ETF",
  BNDX: "Vanguard Total International Bond ETF",
  BNDW: "Vanguard Total World Bond ETF",
  VTC: "Vanguard Total Corporate Bond ETF",
  VTIP: "Vanguard Short-Term Inflation-Protected Securities ETF",

  // iShares/BlackRock ETFs
  IVV: "iShares Core S&P 500 ETF",
  IWM: "iShares Russell 2000 ETF",
  EFA: "iShares MSCI EAFE ETF",
  AGG: "iShares Core U.S. Aggregate Bond ETF",
  IEMG: "iShares Core MSCI Emerging Markets ETF",
  IJH: "iShares Core S&P Mid-Cap ETF",
  IJR: "iShares Core S&P Small-Cap ETF",
  IEFA: "iShares Core MSCI EAFE ETF",
  EEM: "iShares MSCI Emerging Markets ETF",
  IWF: "iShares Russell 1000 Growth ETF",
  IWD: "iShares Russell 1000 Value ETF",
  LQD: "iShares iBoxx Investment Grade Corporate Bond ETF",
  TIP: "iShares TIPS Bond ETF",
  HYG: "iShares iBoxx High Yield Corporate Bond ETF",
  MUB: "iShares National Muni Bond ETF",
  IWB: "iShares Russell 1000 ETF",
  IWR: "iShares Russell Mid-Cap ETF",
  IWS: "iShares Russell Mid-Cap Value ETF",
  IWP: "iShares Russell Mid-Cap Growth ETF",
  IWN: "iShares Russell 2000 Value ETF",
  IWO: "iShares Russell 2000 Growth ETF",
  IWV: "iShares Russell 3000 ETF",
  ITOT: "iShares Core S&P Total U.S. Stock Market ETF",
  IXUS: "iShares Core MSCI Total International Stock ETF",
  IUSB: "iShares Core Total USD Bond Market ETF",
  IAGG: "iShares Core International Aggregate Bond ETF",
  SHY: "iShares 1-3 Year Treasury Bond ETF",
  IEI: "iShares 3-7 Year Treasury Bond ETF",
  IEF: "iShares 7-10 Year Treasury Bond ETF",
  TLT: "iShares 20+ Year Treasury Bond ETF",
  GOVT: "iShares U.S. Treasury Bond ETF",
  EMB: "iShares J.P. Morgan USD Emerging Markets Bond ETF",
  IGIB: "iShares 5-10 Year Investment Grade Corporate Bond ETF",
  IGSB: "iShares 1-5 Year Investment Grade Corporate Bond ETF",
  USIG: "iShares Broad USD Investment Grade Corporate Bond ETF",
  SHV: "iShares Short Treasury Bond ETF",
  FLOT: "iShares Floating Rate Bond ETF",
  ACWI: "iShares MSCI ACWI ETF",
  ACWX: "iShares MSCI ACWI ex U.S. ETF",
  EFV: "iShares MSCI EAFE Value ETF",
  EFG: "iShares MSCI EAFE Growth ETF",
  SCZ: "iShares MSCI EAFE Small-Cap ETF",
  EWJ: "iShares MSCI Japan ETF",
  EWZ: "iShares MSCI Brazil ETF",
  EWT: "iShares MSCI Taiwan ETF",
  EWY: "iShares MSCI South Korea ETF",
  EWC: "iShares MSCI Canada ETF",
  EWG: "iShares MSCI Germany ETF",
  EWU: "iShares MSCI United Kingdom ETF",
  FXI: "iShares China Large-Cap ETF",
  MCHI: "iShares MSCI China ETF",
  INDA: "iShares MSCI India ETF",
  EWA: "iShares MSCI Australia ETF",
  EWQ: "iShares MSCI France ETF",
  EWI: "iShares MSCI Italy ETF",
  EWP: "iShares MSCI Spain ETF",
  EWL: "iShares MSCI Switzerland ETF",
  EWD: "iShares MSCI Sweden ETF",
  EWN: "iShares MSCI Netherlands ETF",
  ERUS: "iShares MSCI Russia ETF",
  TUR: "iShares MSCI Turkey ETF",
  EZA: "iShares MSCI South Africa ETF",
  EWM: "iShares MSCI Malaysia ETF",
  EWS: "iShares MSCI Singapore ETF",
  EWH: "iShares MSCI Hong Kong ETF",
  EPHE: "iShares MSCI Philippines ETF",
  EIDO: "iShares MSCI Indonesia ETF",
  THD: "iShares MSCI Thailand ETF",

  // SPDR ETFs
  SPY: "SPDR S&P 500 ETF Trust",
  GLD: "SPDR Gold Shares",
  XLF: "Financial Select Sector SPDR Fund",
  XLE: "Energy Select Sector SPDR Fund",
  XLK: "Technology Select Sector SPDR Fund",
  XLV: "Health Care Select Sector SPDR Fund",
  XLI: "Industrial Select Sector SPDR Fund",
  XLY: "Consumer Discretionary Select Sector SPDR Fund",
  XLP: "Consumer Staples Select Sector SPDR Fund",
  XLB: "Materials Select Sector SPDR Fund",
  XLU: "Utilities Select Sector SPDR Fund",
  XLRE: "Real Estate Select Sector SPDR Fund",
  XLC: "Communication Services Select Sector SPDR Fund",
  MDY: "SPDR S&P MidCap 400 ETF",
  DIA: "SPDR Dow Jones Industrial Average ETF",
  SDY: "SPDR S&P Dividend ETF",
  SPYG: "SPDR Portfolio S&P 500 Growth ETF",
  SPYV: "SPDR Portfolio S&P 500 Value ETF",
  SPTM: "SPDR Portfolio S&P 1500 Composite Stock Market ETF",
  SPDW: "SPDR Portfolio Developed World ex-US ETF",
  SPEM: "SPDR Portfolio Emerging Markets ETF",
  SPAB: "SPDR Portfolio Aggregate Bond ETF",
  SPSB: "SPDR Portfolio Short Term Corporate Bond ETF",
  SPIB: "SPDR Portfolio Intermediate Term Corporate Bond ETF",
  SPLB: "SPDR Portfolio Long Term Corporate Bond ETF",
  SPTS: "SPDR Portfolio Short Term Treasury ETF",
  SPTI: "SPDR Portfolio Intermediate Term Treasury ETF",
  SPTL: "SPDR Portfolio Long Term Treasury ETF",
  JNK: "SPDR Bloomberg High Yield Bond ETF",
  XOP: "SPDR S&P Oil & Gas Exploration & Production ETF",
  XME: "SPDR S&P Metals and Mining ETF",
  XBI: "SPDR S&P Biotech ETF",
  XRT: "SPDR S&P Retail ETF",
  XHB: "SPDR S&P Homebuilders ETF",
  KRE: "SPDR S&P Regional Banking ETF",
  XAR: "SPDR S&P Aerospace & Defense ETF",
  XTL: "SPDR S&P Telecom ETF",
  XSD: "SPDR S&P Semiconductor ETF",
  XSW: "SPDR S&P Software & Services ETF",
  XTN: "SPDR S&P Transportation ETF",
  XES: "SPDR S&P Oil & Gas Equipment & Services ETF",
  KBE: "SPDR S&P Bank ETF",
  KIE: "SPDR S&P Insurance ETF",

  // Invesco ETFs
  QQQ: "Invesco QQQ Trust",
  QQQM: "Invesco NASDAQ 100 ETF",
  RSP: "Invesco S&P 500 Equal Weight ETF",
  PBW: "Invesco WilderHill Clean Energy ETF",
  QQEW: "Invesco NASDAQ 100 Equal Weight ETF",
  SPHQ: "Invesco S&P 500 Quality ETF",
  SPLV: "Invesco S&P 500 Low Volatility ETF",
  XMLV: "Invesco S&P MidCap Low Volatility ETF",
  XSLV: "Invesco S&P SmallCap Low Volatility ETF",
  SPHD: "Invesco S&P 500 High Dividend Low Volatility ETF",
  PGX: "Invesco Preferred ETF",
  PHO: "Invesco Water Resources ETF",
  PBS: "Invesco Dynamic Media ETF",
  PSI: "Invesco Dynamic Semiconductors ETF",
  PTF: "Invesco DWA Technology Momentum ETF",
  PTH: "Invesco DWA Healthcare Momentum ETF",
  PXI: "Invesco DWA Energy Momentum ETF",
  PFI: "Invesco DWA Financial Momentum ETF",
  PSL: "Invesco DWA Consumer Staples Momentum ETF",
  PEZ: "Invesco DWA Consumer Cyclicals Momentum ETF",
  PRF: "Invesco FTSE RAFI US 1000 ETF",
  PRFZ: "Invesco FTSE RAFI US 1500 Small-Mid ETF",
  PDN: "Invesco FTSE RAFI Developed Markets ex-U.S. ETF",
  PXF: "Invesco FTSE RAFI Developed Markets ex-U.S. Small-Mid ETF",
  DWA: "Invesco DWA NASDAQ Momentum ETF",
  DWAS: "Invesco DWA SmallCap Momentum ETF",
  PDP: "Invesco DWA Momentum ETF",

  // ARK ETFs
  ARKK: "ARK Innovation ETF",
  ARKG: "ARK Genomic Revolution ETF",
  ARKW: "ARK Next Generation Internet ETF",
  ARKF: "ARK Fintech Innovation ETF",
  ARKQ: "ARK Autonomous Technology & Robotics ETF",
  ARKX: "ARK Space Exploration & Innovation ETF",
  PRNT: "The 3D Printing ETF",
  IZRL: "ARK Israel Innovative Technology ETF",

  // Schwab ETFs
  SCHB: "Schwab U.S. Broad Market ETF",
  SCHX: "Schwab U.S. Large-Cap ETF",
  SCHD: "Schwab U.S. Dividend Equity ETF",
  SCHF: "Schwab International Equity ETF",
  SCHE: "Schwab Emerging Markets Equity ETF",
  SCHM: "Schwab U.S. Mid-Cap ETF",
  SCHA: "Schwab U.S. Small-Cap ETF",
  SCHG: "Schwab U.S. Large-Cap Growth ETF",
  SCHV: "Schwab U.S. Large-Cap Value ETF",
  SCHH: "Schwab U.S. REIT ETF",
  SCHC: "Schwab International Small-Cap Equity ETF",
  SCHP: "Schwab U.S. TIPS ETF",
  SCHZ: "Schwab U.S. Aggregate Bond ETF",
  SCHR: "Schwab Intermediate-Term U.S. Treasury ETF",
  SCHO: "Schwab Short-Term U.S. Treasury ETF",
  SCHQ: "Schwab Long-Term U.S. Treasury ETF",
  SCHJ: "Schwab 1-5 Year Corporate Bond ETF",
  SCHI: "Schwab 5-10 Year Corporate Bond ETF",

  // ProShares ETFs
  TQQQ: "ProShares UltraPro QQQ",
  SQQQ: "ProShares UltraPro Short QQQ",
  UPRO: "ProShares UltraPro S&P 500",
  SPXU: "ProShares UltraPro Short S&P 500",
  UDOW: "ProShares UltraPro Dow30",
  SDOW: "ProShares UltraPro Short Dow30",
  URTY: "ProShares UltraPro Russell2000",
  SRTY: "ProShares UltraPro Short Russell2000",
  UMDD: "ProShares UltraPro MidCap400",
  SMDD: "ProShares UltraPro Short MidCap400",
  TNA: "Direxion Daily Small Cap Bull 3X Shares",
  TZA: "Direxion Daily Small Cap Bear 3X Shares",
  FAS: "Direxion Daily Financial Bull 3X Shares",
  FAZ: "Direxion Daily Financial Bear 3X Shares",
  SPXL: "Direxion Daily S&P 500 Bull 3X Shares",
  SPXS: "Direxion Daily S&P 500 Bear 3X Shares",
  TECL: "Direxion Daily Technology Bull 3X Shares",
  TECS: "Direxion Daily Technology Bear 3X Shares",
  SOXL: "Direxion Daily Semiconductor Bull 3X Shares",
  SOXS: "Direxion Daily Semiconductor Bear 3X Shares",
  LABU: "Direxion Daily S&P Biotech Bull 3X Shares",
  LABD: "Direxion Daily S&P Biotech Bear 3X Shares",
  NUGT: "Direxion Daily Gold Miners Index Bull 2X Shares",
  DUST: "Direxion Daily Gold Miners Index Bear 2X Shares",
  JNUG: "Direxion Daily Junior Gold Miners Index Bull 2X Shares",
  JDST: "Direxion Daily Junior Gold Miners Index Bear 2X Shares",
  GUSH: "Direxion Daily S&P Oil & Gas Exp. & Prod. Bull 2X Shares",
  DRIP: "Direxion Daily S&P Oil & Gas Exp. & Prod. Bear 2X Shares",

  // VanEck ETFs
  GDX: "VanEck Gold Miners ETF",
  GDXJ: "VanEck Junior Gold Miners ETF",
  SMH: "VanEck Semiconductor ETF",
  REMX: "VanEck Rare Earth and Strategic Metals ETF",
  SIL: "Global X Silver Miners ETF",
  LIT: "Global X Lithium & Battery Tech ETF",
  COPX: "Global X Copper Miners ETF",
  HACK: "ETFMG Prime Cyber Security ETF",
  FINX: "Global X FinTech ETF",
  BOTZ: "Global X Robotics & Artificial Intelligence ETF",
  CLOU: "Global X Cloud Computing ETF",
  BUG: "Global X Cybersecurity ETF",
  SOCL: "Global X Social Media ETF",
  EDOC: "Global X Telemedicine & Digital Health ETF",
  GNOM: "Global X Genomics & Biotechnology ETF",
  BKCH: "Global X Blockchain ETF",
  POTX: "Global X Cannabis ETF",
  HERO: "Global X Video Games & Esports ETF",
  PAVE: "Global X U.S. Infrastructure Development ETF",
  DRIV: "Global X Autonomous & Electric Vehicles ETF",
  MLPX: "Global X MLP & Energy Infrastructure ETF",
  QYLD: "Global X NASDAQ 100 Covered Call ETF",
  XYLD: "Global X S&P 500 Covered Call ETF",
  RYLD: "Global X Russell 2000 Covered Call ETF",
  DJIA: "Global X Dow 30 Covered Call ETF",
  JEPI: "JPMorgan Equity Premium Income ETF",
  JEPQ: "JPMorgan Nasdaq Equity Premium Income ETF",

  // First Trust ETFs
  FDN: "First Trust Dow Jones Internet Index Fund",
  FXL: "First Trust Technology AlphaDEX Fund",
  FXG: "First Trust Consumer Staples AlphaDEX Fund",
  FXD: "First Trust Consumer Discretionary AlphaDEX Fund",
  FXN: "First Trust Energy AlphaDEX Fund",
  FXO: "First Trust Financials AlphaDEX Fund",
  FXH: "First Trust Health Care AlphaDEX Fund",
  FXR: "First Trust Industrials AlphaDEX Fund",
  FXZ: "First Trust Materials AlphaDEX Fund",
  FXU: "First Trust Utilities AlphaDEX Fund",
  SKYY: "First Trust Cloud Computing ETF",
  CIBR: "First Trust NASDAQ Cybersecurity ETF",
  ROBO: "ROBO Global Robotics and Automation Index ETF",
  FAN: "First Trust Global Wind Energy ETF",
  ICLN: "iShares Global Clean Energy ETF",
  TAN: "Invesco Solar ETF",
  QCLN: "First Trust NASDAQ Clean Edge Green Energy Index Fund",
  PBD: "Invesco Global Clean Energy ETF",
  ACES: "ALPS Clean Energy ETF",
  CTEC: "Global X CleanTech ETF",

  // Other popular ETFs
  VNQ: "Vanguard Real Estate ETF",
  IYR: "iShares U.S. Real Estate ETF",
  RWR: "SPDR Dow Jones REIT ETF",
  SCHH: "Schwab U.S. REIT ETF",
  XLRE: "Real Estate Select Sector SPDR Fund",
  ICF: "iShares Cohen & Steers REIT ETF",
  USRT: "iShares Core U.S. REIT ETF",
  REZ: "iShares Residential and Multisector Real Estate ETF",
  PSR: "Invesco Active U.S. Real Estate Fund",
  REM: "iShares Mortgage Real Estate ETF",
  MORT: "VanEck Mortgage REIT Income ETF",
  RWX: "SPDR Dow Jones International Real Estate ETF",
  VNQI: "Vanguard Global ex-U.S. Real Estate ETF",
  SRVR: "Pacer Benchmark Data & Infrastructure Real Estate SCTR ETF",
  INDS: "Pacer Benchmark Industrial Real Estate SCTR ETF",
  HOMZ: "Hoya Capital Housing ETF",
  REK: "ProShares Short Real Estate",
  DRN: "Direxion Daily Real Estate Bull 3X Shares",
  DRV: "Direxion Daily Real Estate Bear 3X Shares",

  // Commodity ETFs
  GLD: "SPDR Gold Shares",
  IAU: "iShares Gold Trust",
  SLV: "iShares Silver Trust",
  PPLT: "abrdn Physical Platinum Shares ETF",
  PALL: "abrdn Physical Palladium Shares ETF",
  DBA: "Invesco DB Agriculture Fund",
  DBC: "Invesco DB Commodity Index Tracking Fund",
  USO: "United States Oil Fund",
  UNG: "United States Natural Gas Fund",
  BNO: "United States Brent Oil Fund",
  UGA: "United States Gasoline Fund",
  CORN: "Teucrium Corn Fund",
  WEAT: "Teucrium Wheat Fund",
  SOYB: "Teucrium Soybean Fund",
  CANE: "Teucrium Sugar Fund",
  JO: "iPath Series B Bloomberg Coffee Subindex Total Return ETN",
  NIB: "iPath Series B Bloomberg Cocoa Subindex Total Return ETN",
  BAL: "iPath Series B Bloomberg Cotton Subindex Total Return ETN",
  COW: "iPath Series B Bloomberg Livestock Subindex Total Return ETN",
  PDBC: "Invesco Optimum Yield Diversified Commodity Strategy No K-1 ETF",
  FTGC: "First Trust Global Tactical Commodity Strategy Fund",
  COMT: "iShares Commodities Select Strategy ETF",
  COM: "Direxion Auspice Broad Commodity Strategy ETF",

  // Thematic and Sector ETFs
  ICLN: "iShares Global Clean Energy ETF",
  QCLN: "First Trust NASDAQ Clean Edge Green Energy Index Fund",
  TAN: "Invesco Solar ETF",
  FAN: "First Trust Global Wind Energy ETF",
  LIT: "Global X Lithium & Battery Tech ETF",
  BATT: "Amplify Lithium & Battery Technology ETF",
  GRID: "First Trust NASDAQ Clean Edge Smart Grid Infrastructure Index Fund",
  ACES: "ALPS Clean Energy ETF",
  SMOG: "VanEck Low Carbon Energy ETF",
  CTEC: "Global X CleanTech ETF",
  ERTH: "Invesco MSCI Sustainable Future ETF",
  KRBN: "KraneShares Global Carbon Strategy ETF",
  WOOD: "iShares Global Timber & Forestry ETF",
  FILL: "iShares MSCI Global Energy Producers ETF",
  IEO: "iShares U.S. Oil & Gas Exploration & Production ETF",
  IEZ: "iShares U.S. Oil Equipment & Services ETF",
  IXC: "iShares Global Energy ETF",
  AMLP: "Alerian MLP ETF",
  EMLP: "First Trust North American Energy Infrastructure Fund",
  ENFR: "Alerian Energy Infrastructure ETF",
  XOP: "SPDR S&P Oil & Gas Exploration & Production ETF",
  VDE: "Vanguard Energy ETF",
  FENY: "Fidelity MSCI Energy Index ETF",
  RYE: "Invesco S&P 500 Equal Weight Energy ETF",
  JHME: "John Hancock Multifactor Energy ETF",

  // Fixed Income Specialty ETFs
  BSV: "Vanguard Short-Term Bond ETF",
  BIV: "Vanguard Intermediate-Term Bond ETF",
  BLV: "Vanguard Long-Term Bond ETF",
  EDV: "Vanguard Extended Duration Treasury ETF",
  ZROZ: "PIMCO 25+ Year Zero Coupon U.S. Treasury Index ETF",
  TLH: "iShares 10-20 Year Treasury Bond ETF",
  MBB: "iShares MBS ETF",
  CMBS: "iShares CMBS ETF",
  PFF: "iShares Preferred and Income Securities ETF",
  PGF: "Invesco Financial Preferred ETF",
  VRP: "Invesco Variable Rate Preferred ETF",
  FPE: "First Trust Preferred Securities and Income ETF",
  PFFD: "Global X U.S. Preferred ETF",
  PSK: "SPDR Wells Fargo Preferred Stock ETF",
  KBWY: "Invesco KBW Premium Yield Equity REIT ETF",
  SRET: "Global X SuperDividend REIT ETF",
  DIV: "Global X SuperDividend U.S. ETF",
  SDIV: "Global X SuperDividend ETF",
  SDEM: "Global X MSCI SuperDividend Emerging Markets ETF",
  IDV: "iShares International Select Dividend ETF",
  DVYE: "iShares Emerging Markets Dividend ETF",
  DEM: "WisdomTree Emerging Markets High Dividend Fund",
  DWM: "WisdomTree International Equity Fund",
  DTH: "WisdomTree International High Dividend Fund",
  DOL: "WisdomTree International LargeCap Dividend Fund",
  DLS: "WisdomTree International SmallCap Dividend Fund",
  DNL: "WisdomTree Global ex-U.S. Quality Dividend Growth Fund",
  DGRW: "WisdomTree U.S. Quality Dividend Growth Fund",
  DGRS: "WisdomTree U.S. SmallCap Quality Dividend Growth Fund",
  DGRE: "WisdomTree Emerging Markets Quality Dividend Growth Fund",
  DON: "WisdomTree U.S. MidCap Dividend Fund",
  DES: "WisdomTree U.S. SmallCap Dividend Fund",
  DHS: "WisdomTree U.S. High Dividend Fund",
  DTD: "WisdomTree U.S. Total Dividend Fund",
  DMDV: "AAM S&P Developed Markets High Dividend Value ETF",
  VYMI: "Vanguard International High Dividend Yield ETF",
  VIGI: "Vanguard International Dividend Appreciation ETF",
  SCHD: "Schwab U.S. Dividend Equity ETF",
  FDVV: "Fidelity High Dividend ETF",
  FDL: "First Trust Morningstar Dividend Leaders Index Fund",
  FVD: "First Trust Value Line Dividend Index Fund",
  VIG: "Vanguard Dividend Appreciation ETF",
  DGRO: "iShares Core Dividend Growth ETF",
  DIVO: "Amplify CWP Enhanced Dividend Income ETF",
  NOBL: "ProShares S&P 500 Dividend Aristocrats ETF",
}

// Helper function to check if a ticker is a known ETF
export function isKnownETF(ticker: string): boolean {
  return ticker.toUpperCase() in KNOWN_ETF_NAMES
}

// Helper function to get ETF name with fallback
export function getKnownETFName(ticker: string): string | null {
  const upperTicker = ticker.toUpperCase()
  return KNOWN_ETF_NAMES[upperTicker] || null
}

// Import asset classifications for stock name lookup
import assetClassifications from "@/data/asset-classifications.json"

// Helper function to get canonical stock name from asset-classifications
export function getKnownStockName(ticker: string): string | null {
  const upperTicker = ticker.toUpperCase()
  const stockData = assetClassifications.stocks[upperTicker as keyof typeof assetClassifications.stocks]
  return stockData?.name || null
}